### Requisição POST
POST http://localhost:5214/funcionario 
Content-Type: application/json

{
    "Id": "17",
    "Nome": "Olavo",
    "Cargo": "Repositor"
}

### Requisição PUT
PUT http://localhost:5214/funcionario/2 
Content-Type: application/json

{
    "Id": "15",
    "Nome": "Ana",
    "Cargo": "Caixa"
}
    